.dockerignore, .gitignore, Dockerfile, README.md, build.sh, cpp/.gitignore, cpp/CMakeLists.txt, cpp/build.sh, gen_pt_model.sh, java/.gitignore
new builder.sh and apply the container to build the jar and .so files.
=> Dockerize the build process

cpp/src/angel/pytorch/angel_torch.cc
add edge feature for gnn, such as: edge feature, edge label. close #29
=> add edge feature for gnn

cpp/src/angel/pytorch/angel_torch.cc
support high-sparse feature for gnn on pytorch on angel. close #32
=> [New Feature]support high-sparse feature for gnn

cpp/src/angel/pytorch/angel_torch.cc
add feature importance for deep&wide. close #35
=> add feature importance for deep&wide

cpp/include/angel/pytorch/angel_torch.h, cpp/include/angel/pytorch/model.h, cpp/include/angel/pytorch/utils.h, cpp/src/angel/pytorch/angel_torch.cc, cpp/src/angel/pytorch/model.cc, cpp/src/angel/pytorch/utils.cc
support dssm algo on pytorch on angel. close #37
=> [New Feature]Support dssm algo

java/src/main/scala/com/tencent/angel/pytorch/params/HasBatchSizeMultiple.scala, java/src/main/scala/com/tencent/angel/pytorch/params/HasEdgeFeatureDim.scala, java/src/main/scala/com/tencent/angel/pytorch/params/HasEdgeFeaturePath.scala, java/src/main/scala/com/tencent/angel/pytorch/params/HasEdgeType.scala, java/src/main/scala/com/tencent/angel/pytorch/params/HasFeatEmbedDim.scala, java/src/main/scala/com/tencent/angel/pytorch/params/HasFeatEmbedPath.scala, java/src/main/scala/com/tencent/angel/pytorch/params/HasFieldMultiHot.scala, java/src/main/scala/com/tencent/angel/pytorch/params/HasFieldNum.scala, java/src/main/scala/com/tencent/angel/pytorch/params/HasItemFeatEmbedDim.scala, java/src/main/scala/com/tencent/angel/pytorch/params/HasItemFeatureDim.scala, java/src/main/scala/com/tencent/angel/pytorch/params/HasItemFieldNum.scala, java/src/main/scala/com/tencent/angel/pytorch/params/HasItemNumSamples.scala, java/src/main/scala/com/tencent/angel/pytorch/params/HasNodeType.scala, java/src/main/scala/com/tencent/angel/pytorch/params/HasNumLabels.scala, java/src/main/scala/com/tencent/angel/pytorch/params/HasPSModelCheckpoint.scala, java/src/main/scala/com/tencent/angel/pytorch/params/HasPSModelCheckpointInterval.scala, java/src/main/scala/com/tencent/angel/pytorch/params/HasTaskType.scala, java/src/main/scala/com/tencent/angel/pytorch/params/HasUseSharedSamples.scala, java/src/main/scala/com/tencent/angel/pytorch/params/HasUserFeatEmbedDim.scala, java/src/main/scala/com/tencent/angel/pytorch/params/HasUserFeatureDim.scala, java/src/main/scala/com/tencent/angel/pytorch/params/HasUserFieldNum.scala, java/src/main/scala/com/tencent/angel/pytorch/params/HasUserNumSamples.scala, java/src/main/scala/com/tencent/angel/pytorch/params/HasValidate.scala, java/src/main/scala/com/tencent/angel/pytorch/params/HasWeighted.scala
=> add algo params

java/jni/angel/pytorch/angel_torch.h, java/src/main/java/com/tencent/angel/pytorch/Torch.java, java/src/main/java/com/tencent/angel/pytorch/torch/TorchModel.java, java/src/main/scala/com/tencent/angel/pytorch/examples/supervised/cluster/RGCNExample.scala, java/src/main/scala/com/tencent/angel/pytorch/examples/supervised/cluster/RecommendationExample.scala
=> update jni method interface

python/graph/graphsage.py, python/graph/nn/conv/sage_conv.py
abstract convolution operator for graphsage. close #48
=> [New Feature] abstract convolution operator for graphsage

python/graph/edgeprop.py, python/graph/nn/conv/__init__.py, python/graph/nn/conv/sage_conv.py
support edgeProp algo on pytorch on angel. close #43
=> [New Feature] support edgeProp algo

python/graph/nn/conv/__init__.py, python/graph/nn/conv/igmc_conv.py, python/graph/supervised_igmc.py
support IGMC algo on pytorch on angel. close #44
=> [New Feature]support IGMC algo

python/graph/nn/conv/__init__.py, python/graph/nn/conv/bisage_conv.py, python/graph/semi_bipartite_graphsage.py, python/graph/unsupervised_bipartite_graphsage.py
support bipartite graphsage on Pytorch on Angel. close #31
=> [New Feature]support bipartite graphsage

python/graph/nn/conv/__init__.py, python/graph/nn/conv/hgat_conv.py, python/graph/unsupervised_heterogeneous_gat.py
support HGAT algo on pytorch on angel. closes #45 closes #32
=> [New Feature] support HGAT algo

python/graph/nn/conv/__init__.py, python/graph/nn/conv/han_conv.py, python/graph/semi_han.py
support semi han algo on pytorch on angel. close #45
=> [New Feature] support semi han algo

python/graph/unsupervised_graphsage.py
support unsupervised graphsage algo on pytorch on angel. close #56
=> [New Feature]support unsupervised graphsage algo

python/graph/rgcn.py
support multi-label-classification and class-weight for rgcn on pytorch on angel. close #61
=> support multi-label-classification and class-weight for rgcn

python/graph/utils/softmax.py
fix bug about softmax method, close #63
=> fix bug about softmax

python/graph/edgeprop.py, python/graph/nn/conv/sage_conv.py, python/graph/utils/process_data.py
=> fix bug: edgeprop

python/graph/gat.py, python/graph/nn/conv/__init__.py, python/graph/nn/conv/gat_conv.py
support GAT algorithm on pytorch on angel. close #72
=> [New Feature]support gat algo

java/src/main/scala/com/tencent/angel/pytorch/graph/gcn/GNN.scala
fix bug: reset feature_dim in high-sparse
=> fix gnn about feature_dim

cpp/CMakeLists.txt
add some parameters to CMakeLists. close #76
=> add some parameters to CMakeLists

java/src/main/scala/com/tencent/angel/pytorch/graph/gcn/SparseGNNPSModel.scala
SparseGNNPSModel adapt hash partition. close #78
=> SparseGNNPSModel adapt hash partition

docs/graph.md
add docs for dgi, rgcn,edgeprop. close #80
=> add docs for dgi, rgcn,edgeprop

java/src/main/scala/com/tencent/angel/pytorch/examples/unsupervised/cluster/DGIExample.scala, java/src/main/scala/com/tencent/angel/pytorch/graph/gcn/hetAttention/HAN.scala
fix han feature dim error for sparse input
=> fix han feature dim error for sparse input

python/graph/nn/conv/han_conv.py, python/graph/semi_han.py
=> fix han definition bug

java/src/main/scala/com/tencent/angel/pytorch/examples/supervised/cluster/BiGCNExample.scala, java/src/main/scala/com/tencent/angel/pytorch/examples/supervised/cluster/GATExample.scala, java/src/main/scala/com/tencent/angel/pytorch/examples/supervised/cluster/GCNExample.scala, java/src/main/scala/com/tencent/angel/pytorch/examples/supervised/cluster/GraphSageExample.scala, java/src/main/scala/com/tencent/angel/pytorch/examples/supervised/cluster/HANExample.scala
1. correct han sparse relevant params
2. disable useSharedSamples param for sparse feature input
=> fix example params error

cpp/src/angel/pytorch/utils.cc, docs/recommendation.md, java/src/main/scala/com/tencent/angel/pytorch/examples/supervised/cluster/ESMMExample.scala, java/src/main/scala/com/tencent/angel/pytorch/model/ParTorchModel.scala, python/recommendation/esmm.py
=> [85]add esmm

java/src/main/scala/com/tencent/angel/pytorch/examples/supervised/cluster/AggregatorExample.scala, java/src/main/scala/com/tencent/angel/pytorch/examples/supervised/cluster/GAMLPExample.scala, java/src/main/scala/com/tencent/angel/pytorch/examples/supervised/cluster/HeteAggregatorExample.scala, java/src/main/scala/com/tencent/angel/pytorch/graph/gcn/GAMLP.scala, java/src/main/scala/com/tencent/angel/pytorch/graph/gcn/GraphPartition.scala, java/src/main/scala/com/tencent/angel/pytorch/graph/gcn/HAggregator.scala, java/src/main/scala/com/tencent/angel/pytorch/graph/gcn/HAggregatorPartition.scala, java/src/main/scala/com/tencent/angel/pytorch/graph/gcn/MakeEdgeIndex.scala, java/src/main/scala/com/tencent/angel/pytorch/params/HasUseWeightedAggregate.scala
=> 增加GAMLP同构及异构部分

docs/graph.md, python/graph/aggregator.py, python/graph/gamlp.py
添加说明文档和aggregator.py和gamlp.py文件
=> 添加说明文档和aggregator.py和gamlp.py文件

java/src/main/scala/com/tencent/angel/pytorch/graph/gcn/HGNNPSModel.scala
=> 添加HGNNPSModel

java/src/main/scala/com/tencent/angel/pytorch/graph/gcn/HGNNPartition.scala
=> 添加HGNNPartition类

java/src/main/scala/com/tencent/angel/pytorch/graph/gcn/EmbeddingGNNPSModel.scala
=> 添加EmbeddingGNNPSModel类

java/src/main/scala/com/tencent/angel/pytorch/init/Constant.scala, java/src/main/scala/com/tencent/angel/pytorch/init/InitMethod.scala, java/src/main/scala/com/tencent/angel/pytorch/init/InitUtils.scala, java/src/main/scala/com/tencent/angel/pytorch/init/RandomNormal.scala, java/src/main/scala/com/tencent/angel/pytorch/init/RandomUniform.scala, java/src/main/scala/com/tencent/angel/pytorch/init/XavierOrKaimingNormal.scala, java/src/main/scala/com/tencent/angel/pytorch/init/XavierOrKaimingUniform.scala
=> 添加embedding的初始化类

java/src/main/java/com/tencent/angel/pytorch/data/SampleParser.java, java/src/main/scala/com/tencent/angel/pytorch/graph/gcn/MakeSparseBiFeature.scala, java/src/main/scala/com/tencent/angel/pytorch/io/DataLoaderUtils.scala, java/src/main/scala/com/tencent/angel/pytorch/io/IOFunctions.scala
=> gatne需要的加载函数、特征处理函数添加

cpp/include/angel/pytorch/angel_torch.h, cpp/include/angel/pytorch/model.h, cpp/include/angel/pytorch/utils.h, cpp/src/angel/pytorch/angel_torch.cc, cpp/src/angel/pytorch/utils.cc, java/src/main/java/com/tencent/angel/pytorch/Torch.java, java/src/main/java/com/tencent/angel/pytorch/torch/TorchModel.java
=> gatne修改对应的c++部分

java/src/main/scala/com/tencent/angel/pytorch/examples/supervised/cluster/AggregatorExample.scala, java/src/main/scala/com/tencent/angel/pytorch/examples/supervised/cluster/GAMLPExample.scala, java/src/main/scala/com/tencent/angel/pytorch/examples/supervised/cluster/HeteAggregatorExample.scala, java/src/main/scala/com/tencent/angel/pytorch/examples/unsupervised/cluster/GATNEExample.scala, java/src/main/scala/com/tencent/angel/pytorch/io/IOFunctions.scala
=> gatneExample类添加
